- name: disable default nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs 22
  ansible.builtin.command: dnf module enable nodejs:22 -y

- name: install nodejs and mysql and npm
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
  - nodejs
  - mysql-server
  - npm

- name: create expense user 
  ansible.builtin.user:
    name: expense

- name: import tasks from common role
  tags:
  - deployment
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: Install mysql2 using Ansible's npm module
  tags:
  - deployment
  community.general.npm:
    name: mysql2
    path: /app

- name: copy backend service file # copy module only works for files without variables
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: ansible to install pymysql and cryptography
  ansible.builtin.pip:
    name: 
    - PyMySQL
    - cryptography
    executable: pip3.9

- name: import mysql data
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ login_host }}"
    target: /app/schema/backend.sql
    name: all
    state: import

- name: daemon reload
  tags:
  - deployment
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: backend
    enabled: true

